# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

ref:
  # the star index location or genomefa to index
  index: "MGAS5005"
  genomefa: "/data/gpfs/assoc/inbre/projects/paul_sumday/rnaseq_from2019/refs/MGAS5005.fasta"
  # gtf file with transcripts
  annotation: "/data/gpfs/assoc/inbre/projects/paul_sumday/rnaseq_from2019/refs/MGAS5005.gffread.CDS.gtf"
  adapter: "/data/gpfs/assoc/inbre/projects/common_references/CustomBlacklist.fa"

params:
  ##Comma seperated list of aligners: Currnet options are star and hisat2. Only listing one will only run 1 aligner
  aligners: "hisat2"
  trimmers: "fastp"
  pese: "se"
  star: ""
  hisat2: ""
  #featurecounts: "-p -C -t exon -g gene_id --extraAttributes transcript_id"
  #featurecounts: "-p -C -t exon -g gene_id --extraAttributes transcript_id"
  featurecounts: "-p -C -t exon -g transcript_id,Dbxref,ID,Parent,gbkey,gene,product,gene,inference,product"
  featurecountsse: "-t CDS -g transcript_id --extraAttributes gene_name,Dbxref,Name,gbkey,gene,inference,locus_tag,product,protein_id"
  featurecountsmulti: "-p -M -t exon -g gene_id --extraAttributes gene_biotype,transcript_id,transcript_biotype,gene_name,transcript_name"
