# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

ref:
  # name of index folder within the current directory
  index: "ATL_v3"
  genomefa: "/data/gpfs/assoc/inbre/projects/common_references/ATL_v3_spuddb/ATL_v3.asm.fa"
  #Transcriptomefa can be left blank unless using salmon
  transcriptomefa: "/data/gpfs/assoc/inbre/projects/helen_wing/rnaseq_training/ref/cds_from_genomic.fna"
  # gtf or gff file with transcripts
  #annotation: "/data/gpfs/assoc/inbre/projects/helen_wing/rnaseq_training/ref/genomic.gtf"
  annotation: "/data/gpfs/assoc/inbre/projects/common_references/ATL_v3_spuddb/ATL_v3.hc_gene_models.gff3"
  #DEPRECATED (unused)
  adapter: "/data/gpfs/assoc/inbre/projects/common_references/CustomBlacklist.fa"

params:
  ##Comma seperated list of aligners: Currnet options are star, hisat2, and salmon. Only listing one will only run 1 aligner
  #aligners: "hisat2,star,salmon"
  aligners: "star"
  ##Comma seperated list: Currnet options are fastp, trimmomatic, trimgalore
  trimmers: "fastp,trimgalore"
  ##Comma seperated list: Currnet options are pe or se (can't mix data types in a run)
  pese: "pe"
  star: ""
  fastp: "--trim_poly_g"
  starindex: ""
  hisat2: ""
  hisat2index: ""
  #featurecounts: "-p -C -t exon -g gene_id --extraAttributes transcript_id"
  #featurecounts: "-p -C -t exon -g gene_id --extraAttributes transcript_id"
  #featurecounts: "-p -C -t CDS,rRNA -g gene_id --extraAttributes transcript_id,gene,gbkey,locus_tag,product,protein_id,note"
  featurecounts: "-p -B -C -t exon -g Parent"
  featurecountsse: "-t CDS -g transcript_id --extraAttributes gene_name,Dbxref,Name,gbkey,gene,inference,locus_tag,product,protein_id"
  #featurecountsmulti: "-p -M -t exon -g gene_id --extraAttributes transcript_id"
  #featurecountsmultifrac: "-p -M --fraction -t exon -g gene_id --extraAttributes transcript_id"
  featurecountsmulti: "-p -M -t CDS,rRNA,tRNA -g ID --extraAttributes Dbxref,Name,transcript_id,gene,gbkey,locus_tag,product,protein_id,Note"
  featurecountsmultifrac: "-p -M --fraction -t CDS,rRNA,tRNA -g ID --extraAttributes Dbxref,Name,transcript_id,gene,gbkey,locus_tag,product,protein_id,Note"
